name: Deploy to Amazon EC2

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: copy files to ec2
      uses: appleboy/scp-action@master
      with:
        host: ec2-3-68-94-147.eu-central-1.compute.amazonaws.com
        username: ubuntu
        key: "${{ secrets.AMAZON_SSH }}"
        source: .
        target: /home/ubuntu/code

    - name: execute remote commands
      uses: appleboy/ssh-action@master
      with: 
        host: ec2-3-68-94-147.eu-central-1.compute.amazonaws.com
        username: ubuntu
        key: "${{ secrets.AMAZON_SSH }}"
        script: |
          cd /home/ubuntu/front
          docker compose up

