name: Deploy to Amazon EC2

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: copy files to ec2
      uses: appleboy/scp-action@master
      with:
        host: ec2-3-79-244-54.eu-central-1.compute.amazonaws.com
        username: ubuntu
        key: "${{ secrets.AMAZON_SSH }}"
        source: .
        target: /home/ubuntu/front

    - name: execute remote commands
      uses: appleboy/ssh-action@master
      with: 
        host: ec2-3-79-244-54.eu-central-1.compute.amazonaws.com
        username: ubuntu
        key: "${{ secrets.AMAZON_SSH }}"
        script: |
          cd /home/ubuntu/front
          docker compose down
          docker image prune -f
          docker compose up -d --build
